### ISSUE TITLE
About turing off annotationPosition

### ISSUE THREAD

**Issue by elisabettasciacca** [KatrionaGoldmann/glmmSeq#19]
Hi Kat, 

I have a minor issue. 
I don't know if you had a particular idea in mind when you set up `annotationPosition` to `TRUE ` in the fcPlot (line 212, fcPlot.R). 
If there's no specif reason, I would turn it off by default as I find it very annoying when I try to move gene labels and I move the arrow instead by mistake. This makes me loose the original position of the label and it's difficult to put it back to the original dot. 
From the related [plotly code](https://github.com/plotly/plotly.js/blob/master/src/plot_api/plot_config.js): 

> `annotationPosition `determines if the main anchor of the annotation is editable. The main anchor corresponds to the text (if no arrow) or the arrow (which drags the whole thing leaving the arrow length & direction unchanged).

If you turn it off the label movement will still be assured by `annotationText = TRUE` and `annotationTail = TRUE`.

**Comment by KatrionaGoldmann** [comment]
This is a hang over from a specific instance I was working on. I have set it to FALSE in v0.2.1

**Comment by elisabettasciacca** [comment]
Perfect, thanks!
