### ISSUE TITLE
Add '...' to fcPlot 

### ISSUE THREAD

**Issue by elisabettasciacca** [KatrionaGoldmann/glmmSeq#21]
Hi Kat, 

I'm working at a shiny app where I want to interactively show a pairedPlot when a gene is clicked on the fcPlot. 
To do this I need to populate two more options of the plotly fcPlot: `source` and `key`. If would just add `... ` among your fcPlot options and then to your plotly call (line #195) this would be easily allowed. 

Thanks!!

**Comment by KatrionaGoldmann** [comment]
Good point. Added in v0.2.1 where ... passed to either plotly(...) or ggplot(...) respectively. 

Thanks.
