### ISSUE TITLE
mention size factors in the vignette

### ISSUE THREAD

**Issue by elisabettasciacca** [KatrionaGoldmann/glmmSeq#8]
Although it's optional, the vignette could mention that we can specify size factors as offsets to be included in the linear predictor during fitting. 
Three options to get size factors are: 
- Manually: 
```
sizeFactors <- colSums(tpmdata)  #total no of reads 
sizeFactors <- sizeFactors2 / mean(sizeFactors2)  #scale so that mean=1 (normalise) 
```

- edgeR:
`sizeFactors <- calcNormFactors(counts, method="TMM")`
- DESeq2:
`sizeFactors <- estimateSizeFactorsForMatrix(tpmdata)`

**Comment by KatrionaGoldmann** [comment]
Good idea Elisabetta. At the same time we should probably add additional examples for calculating the dispersion (e.g. using DESeq2).

**Comment by elisabettasciacca** [comment]
Agreed.
Here three options for dispersions: 

manually:
		`dispersions <- apply(tpm, 1, function(x){(var(x, na.rm=TRUE)-mean(x, na.rm=TRUE))/(mean(x, na.rm=TRUE)**2)})`

edgeR:
```
dge <- DGEList(tpm)
dispersions <- estimateCommonDisp(dge)
```

DESeq2:
```
dds <- DESeqDataSetFromTximport(txi = txi, colData = metadata, design = ~ 1)
dds <- DESeq(dds)
dispersions <- setNames(dispersions(dds), rownames(txi$abundance))
```

Hope this helps. 
Eli

**Comment by KatrionaGoldmann** [comment]
I've added these to the vignette 👍
